# Generated by Django 5.0.4 on 2024-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_historicalperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
