# Generated by Django 5.0.4 on 2024-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_remove_purchaseorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='Order Placed', max_length=50),
        ),
    ]
