# Generated by Django 5.0.4 on 2024-05-06 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_purchaseorder_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 17, 23, 25, 397720, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
